spring:
  application:
    name: mechanical-workshops

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

  datasource:
    url: jdbc:postgresql://localhost:5432/mechanical-workshops
    username: postgres
    password: system
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none  # Opciones: none, update, create, create-drop
    show-sql: true  # Mostrar consultas SQL en consola
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  servlet:
    context-path: /api

cron:
  job:
    generar-turnos: "0 0 6 * * ?"

logging:
  level:
    org:
      springframework:
        security: DEBUG


